;
; File generated by cc65 v 2.19 - Git 43c2239e9
;
	.fopt		compiler,"cc65 v 2.19 - Git 43c2239e9"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.forceimport	initmainargs
	.import		_SDL_Init
	.import		_SDL_Quit
	.import		_SDL_GetRelativeMouseState
	.import		_stderr
	.import		_fprintf
	.import		_printf
	.export		_main

.segment	"RODATA"

S0002:
	.byte	$50,$72,$6F,$67,$72,$61,$6D,$6D,$65,$20,$64,$65,$6D,$61,$72,$72
	.byte	$65,$2E,$20,$41,$70,$70,$75,$79,$65,$7A,$20,$73,$75,$72,$20,$45
	.byte	$43,$48,$41,$50,$20,$70,$6F,$75,$72,$20,$71,$75,$69,$74,$74,$65
	.byte	$72,$2E,$0A,$00
S0001:
	.byte	$45,$72,$72,$65,$75,$72,$20,$64,$27,$69,$6E,$69,$74,$69,$61,$6C
	.byte	$69,$73,$61,$74,$69,$6F,$6E,$20,$64,$65,$20,$6C,$61,$20,$53,$44
	.byte	$4C,$20,$28,$45,$56,$45,$4E,$54,$53,$29,$0A,$00
S0003:
	.byte	$78,$3A,$25,$64,$20,$79,$3A,$25,$64,$0A,$00

; ---------------------------------------------------------------
; int __near__ __cdecl__ main (int argc, char **argv)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$01
	jsr     pusha
	jsr     decsp2
	ldx     #$00
	lda     #$01
	jsr     _SDL_Init
	jmp     L0002
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$04
	jsr     _fprintf
	ldx     #$00
	lda     #$01
	jmp     L0001
L0002:	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldy     #$02
	jsr     _printf
	jmp     L0005
L0003:	lda     #$01
	jsr     leaa0sp
	jsr     pushax
	lda     #$02
	jsr     leaa0sp
	jsr     _SDL_GetRelativeMouseState
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldy     #$03
	ldx     #$00
	lda     (c_sp),y
	bpl     L0006
	dex
L0006:	jsr     pushax
	ldy     #$04
	ldx     #$00
	lda     (c_sp),y
	bpl     L0007
	dex
L0007:	jsr     pushax
	ldy     #$06
	jsr     _printf
L0005:	ldy     #$02
	lda     (c_sp),y
	jne     L0003
	jsr     _SDL_Quit
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

