.export _SDL_GetError

.import SDL_GetError

.proc _SDL_GetError
    ;;@proto const char* _SDL_GetError(void);
    ;;@brief Get the last error message from SDL.
    ;;@details This function returns a string containing the last error message generated by SDL functions. The returned string is valid until the next call to an SDL function that generates an error.
    ;;@returns A pointer to a string containing the last error message, or an empty string if there is no error.
    ;;@note The actual implementation is in SDL_GetError.s. This is a wrapper function.

    jmp    SDL_GetError ; SDL_GetError is implemented in SDL_GetError.s
.endproc
