site_name: SDL LIB DOCUMENTATION

site_dir: ../docs/

markdown_extensions:
    - pymdownx.tabbed:
        alternate_style: true
    - admonition

extra:
  version:
    provider: mike
    alias:
      dev: "2026.3 (dev)"

plugins:
    - git-revision-date
    - search
    - markmap


dev_addr: '172.30.72.43:8002'

theme:
    name: material
    features:
      - search.suggest
      - search.highlight
      - search.share
nav:
    - C Functions:
        - Window:
            - SDL_CreateWindow(): _SDL_CreateWindow.md
            - SDL_Delay(): _SDL_Delay.md
            - SDL_DestroyWindow(): _SDL_DestroyWindow.md
            - SDL_FreeSurface(): _SDL_FreeSurface.md
            - SDL_GetError(): _SDL_GetError.md
            - SDL_GetWindowSurface(): _SDL_GetWindowSurface.md
            - SDL_BlitSurface(): _SDL_BlitSurface.md
            - SDL_Init(): _SDL_Init.md
            - SDL_Quit(): _SDL_Quit.md
        - Images:
            - IMG_GetError(): _IMG_GetError.md
            - IMG_Init(): _IMG_Init.md
            - IMG_Load(): _IMG_Load.md
        - mouse:
            - SDL_GetRelativeMouseState(): _SDL_GetRelativeMouseState.md

    - Assembly Routines:
        - Main routines:
            - SDL_BlitSurface: SDL_BlitSurface.md
            - SDL_CreateTextureFromSurface: SDL_CreateTextureFromSurface.md
            - SDL_CreateWindow: SDL_CreateWindow.md
            - SDL_Delay: SDL_Delay.md
            - SDL_DestroyWindow: SDL_DestroyWindow.md
            - SDL_FreeSurface: SDL_FreeSurface.md
            - SDL_GetRelativeMouseState: SDL_GetRelativeMouseState.md
            - SDL_GetWindowSurface: SDL_GetWindowSurface.md
            - SDL_Init: SDL_Init.md
            - SDL_Quit: SDL_Quit.md
            - sdl_get_surface_data_ptr_by_id: sdl_get_surface_data_ptr_by_id.md
            - sdl_new_surface: sdl_new_surface.md
            - sdl_surface_update_with_size_by_id: sdl_surface_update_with_size_by_id.md
        - Image Functions:
            - IMG_GetError: IMG_GetError.md
            - IMG_Init: IMG_Init.md
            - IMG_Load: IMG_Load.md
    - Examples:
        - C: c/surface.md

